name: diwgtest
channels:
  - conda-forge
dependencies:
  - python==3.12
  - gdal
  - pytest
  - pytest-html
  - pytest-json-report
  - pytest-md
  - udunits2
  - cfunits
  - dateparser
  - weasyprint
